name: EMS
channels:
  - conda-forge
  - defaults
dependencies:
  - blas[build=mkl]
  - python=3.11
  - pandas
  - google-auth
  - dask
  - dask-jobqueue
#  - coiled
  - pip
  - pip:
    - git+https://github.com/adonoho/EMS.git@v0.0.17
variables:
  MKL_NUM_THREADS: '1'
  OPENBLAS_NUM_THREADS: '1'
